- alias: "Outdoor Lights On When Dark"
  trigger: 
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: -4.0
  action:
    service: switch.turn_on
    entity_id: 
      - switch.front_door_south_switch
      - switch.garage_sconces_switch

- alias: "Porch Light Off At 11"
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: switch.turn_off
    entity_id:
      - switch.front_door_south_switch

- alias: "Outdoor Lights Off When Light"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    above: -4.0
  action:
    service: switch.turn_off
    entity_id: 
      - switch.front_door_south_switch
      - switch.garage_sconces_switch

- alias: "Switch Kitchen Under Cabinet Lights On"
  trigger:
    platform: state
    entity_id: switch.kitchen_south_switch
    to: 'on'
  action:
    service: light.turn_on
    entity_id: 
      - light.kitchen_light_controller

- alias: "Switch Kitchen Under Cabinet Lights Off"
  trigger:
    platform: state
    entity_id: switch.kitchen_south_switch
    to: 'off'
  action:
    service: light.turn_off
    entity_id: 
      - light.kitchen_light_controller

- alias: "Dim theater lights for movies"
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('media_player.home_theater_tv', 'source', 'Plex') }}"
    - platform: template
      value_template: "{{ is_state_attr('media_player.home_theater_tv', 'source', 'Amazon Prime Video') }}"
    - platform: template
      value_template: "{{ is_state_attr('media_player.home_theater_tv', 'source', 'Netflix') }}"
    - platform: template
      value_template: "{{ is_state_attr('media_player.home_theater_tv', 'source', 'Google Play Movies & TV') }}"      
    - platform: template
      value_template: "{{ is_state_attr('media_player.home_theater_tv', 'source', 'Hulu') }}"      
  condition:
    condition: state
    entity_id: light.home_theater_west_dimmer
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.home_theater_west_dimmer
    data:
      brightness_pct: 10
      transition: 3

- alias: "Change light color for watching TV"
  trigger:
    platform: state
    entity_id: media_player.home_theater_tv
    from: 'off'
  action:
    - service: light.turn_off
      entity_id: light.basement_rgbw_controller_red    
    - service: light.turn_off
      entity_id: light.basement_rgbw_controller_green
    - service: light.turn_off
      entity_id: light.basement_rgbw_controller_blue
    - service: light.turn_on
      entity_id: light.basement_rgbw_controller_white
      data:
        transition: 5
        brightness_pct: 30

- alias: "Brighten lights when done watching TV"
  trigger:
    platform: state
    entity_id: media_player.home_theater_tv
    to: 'off'
  condition:
    condition: state
    entity_id: light.home_theater_west_dimmer
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.home_theater_west_dimmer
    data:
      brightness_pct: 100
      transition: 3

- alias: "Change light color when done watching TV"
  trigger:
    platform: state
    entity_id: media_player.home_theater_tv
    to: 'off'
  action:
    service: light.turn_on
    entity_id: light.basement_rgbw_controller_main
    data:
      rgb_color: [255, 255, 255]
      transition: 5
      white_value: 255