- alias: "Turn on porch light when it's dark outside"
  trigger: 
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: -4.0
  action:
    service: switch.turn_on
    entity_id: switch.aeotec_dsc26103_micro_switch_2nd_edition_switch

- alias: "Turn off porch light when it's light outside"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    above: -4.0
  action:
    service: switch.turn_off
    entity_id: switch.aeotec_dsc26103_micro_switch_2nd_edition_switch

- alias: "Turn on Nest Away Mode when the phones are outside the network"
  trigger:
    platform: state
    entity_id: group.devices
    from: 'home'
    to: 'not_home'
    for:
      minutes: 30
  action:
    - service: nest.set_mode
      data:
        home_mode: away

- alias: "Turn off Nest Away Mode when a phone is inside the network"
  trigger: 
    platform: state
    entity_id: group.devices
    from: 'not_home'
    to: 'home'
  action:
    - service: nest.set_mode
      data:
        home_mode: home