- id: outdoor_lights_on_when_dark
  alias: Outdoor Lights On When Dark
  trigger:
  - entity_id: sensor.outside_light
    platform: numeric_state
    for: 00:01:00
    below: '25'
  action:
  - service: scene.turn_on
    entity_id: scene.outdoor_lights_on
  mode: single
- id: porch_light_off_at_11
  alias: House Lights Off At 11
  trigger:
  - at: '23:00:00'
    platform: time
  action:
  - service: scene.turn_on
    entity_id: scene.house_outdoor_lights_off
  - service: light.turn_off
    data: {}
    entity_id: light.wled
  mode: single
- id: outdoor_lights_off_when_light
  alias: Outdoor Lights Off When Light
  trigger:
  - platform: numeric_state
    entity_id: sensor.outside_light
    above: '50'
  action:
  - service: scene.turn_on
    entity_id: scene.all_outdoor_lights_off
  mode: single
- id: dim_theater_lights_for_movies
  alias: Dim theater lights for movies
  trigger:
  - platform: template
    value_template: '{{ is_state_attr(''media_player.home_theater_tv'', ''source'',
      ''Plex'') }}'
  - platform: template
    value_template: '{{ is_state_attr(''media_player.home_theater_tv'', ''source'',
      ''Amazon Prime Video'') }}'
  - platform: template
    value_template: '{{ is_state_attr(''media_player.home_theater_tv'', ''source'',
      ''Netflix'') }}'
  - platform: template
    value_template: '{{ is_state_attr(''media_player.home_theater_tv'', ''source'',
      ''Google Play Movies & TV'') }}'
  - platform: template
    value_template: '{{ is_state_attr(''media_player.home_theater_tv'', ''source'',
      ''Hulu'') }}'
  - platform: template
    value_template: '{{ is_state_attr(''media_player.home_theater_tv'', ''source'',
      ''Disney+'') }}'
  - entity_id: sensor.harmony_hub
    platform: state
    to: Watch a Movie
  - entity_id: media_player.chromecastultra9136
    from: 'off'
    platform: state
    to: idle
  - platform: state
    entity_id: media_player.chromecastultra9136
    from: 'off'
    to: playing
  - platform: state
    entity_id: media_player.chromecastultra9136
    from: 'off'
    to: paused
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.watching_a_movie
      transition: 5
  mode: single
- id: brighten_lights_when_done_watching_tv
  alias: Brighten home theater lights when done watching TV
  trigger:
  - entity_id: media_player.home_theater_tv
    platform: state
    to: 'off'
  action:
  - service: scene.turn_on
    data:
      transition: 5
    target:
      entity_id: scene.done_watching_a_movie
  mode: single
- id: turn_off_home_theater_lights_if_basement_lights_turn_off
  alias: Turn off home theater lights if basement lights turn off
  trigger:
  - platform: state
    entity_id: light.basement_track
    to: 'off'
    for: 0:00:05
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: switch.home_theater_east
      state: 'on'
    - condition: state
      entity_id: light.home_theater_west
      state: 'on'
  action:
  - service: scene.turn_on
    entity_id: scene.basement_lights_off
  mode: single
- id: notify_when_garage_is_open_for_too_long
  alias: Notify when garage is open for too long
  trigger:
  - platform: state
    entity_id: binary_sensor.garage_door_open
    to: 'on'
    for: '1:00:00'
  action:
  - service: camera.snapshot
    data:
      filename: /tmp/garage
    target:
      entity_id: camera.garage_2
  - service: notify.pushover
    data_template:
      message: The garage door has been open longer than an hour
    data:
      title: Garage Door Open
      data:
        sound: gamelan
        attachment: /tmp/garage
  mode: single
- id: notify_when_tv_has_been_on_for_too_long
  alias: Notify when TV has been on for too long
  trigger:
  - entity_id: media_player.home_theater_tv
    for: '3:00:00'
    platform: state
    to: 'on'
  action:
  - data:
      data:
        sound: gamelan
      title: TV is On
    data_template:
      message: The TV has been on for longer than 3 hours
    service: notify.pushover
- id: change_printer_lights_when_printer_is_done_printing
  alias: Change printer lights when printer is done printing
  trigger:
  - entity_id: binary_sensor.octoprint_printing
    platform: state
    to: 'off'
  action:
  - data:
      white_value: 0
    entity_id: light.3d_printer_lights
    service: light.turn_on
  - delay: 00:00:03
  - data:
      effect: colorloop
    entity_id: light.3d_printer_lights
    service: light.turn_on
  - delay: 00:10:00
  - condition: state
    entity_id: binary_sensor.octoprint_printing
    state: 'off'
  - data: {}
    entity_id: light.3d_printer_lights
    service: light.turn_off
  mode: single
- id: turn_3d_printer_light_to_white_when_printing
  alias: Turn 3D printer light to white when printing
  trigger:
  - entity_id: binary_sensor.octoprint_printing
    platform: state
    to: 'on'
  action:
  - data:
      white_value: 255
    entity_id: light.3d_printer_lights
    service: light.turn_on
  - data:
      rgb_color:
      - 255
      - 255
      - 255
    entity_id: light.3d_printer_lights
    service: light.turn_on
  mode: single
- id: turn_garage_interior_lights_on_when_garage_door_opens
  alias: Turn garage interior lights on when garage door opens
  trigger:
  - entity_id: binary_sensor.garage_door_open
    platform: state
    to: 'on'
  condition:
  - condition: sun
    after: sunset
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.garage_interior
  mode: single
- id: turn_garage_interior_lights_off_when_garage_door_closes
  alias: Turn garage interior lights off when garage door closes
  trigger:
  - entity_id: binary_sensor.garage_door_open
    platform: state
    to: 'off'
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.garage_interior
  mode: single
- id: '1566659647483'
  alias: Turn garage interior lights on if door open and sunset
  trigger:
  - event: sunset
    platform: sun
  condition:
  - condition: state
    entity_id: binary_sensor.garage_door_open
    state: 'on'
  action:
  - data: {}
    service: switch.turn_on
    target:
      entity_id: switch.garage_interior
  mode: single
- id: '1577140055130'
  alias: Notify when Hyperion has left the network
  description: ''
  trigger:
  - entity_id: device_tracker.hyperion
    from: home
    platform: state
  condition: []
  action:
  - data:
      message: The Pi may need rebooted. Nginx is down.
      title: Hyperion has left the network
    service: notify.pushover
- id: '1588540340794'
  alias: Set input boolean when home theater is on
  description: ''
  trigger:
  - entity_id: sensor.harmony_hub
    from: PowerOff
    platform: state
  condition: []
  action:
  - entity_id: input_boolean.home_theater_on
    service: input_boolean.turn_on
- id: '1588540420902'
  alias: Set input boolean when home theater is off
  description: ''
  trigger:
  - entity_id: sensor.harmony_hub
    platform: state
    to: PowerOff
  condition: []
  action:
  - entity_id: input_boolean.home_theater_on
    service: input_boolean.turn_off
- id: '1590692559020'
  alias: Wind Gust
  description: ''
  trigger:
  - above: '20'
    entity_id: sensor.outside_wind_gust
    platform: numeric_state
  condition: []
  action:
  - data_template:
      message: Wind is gusting; currently {{ trigger.to_state.state }}mph
      title: High winds at home
    service: notify.pushover
  mode: single
- id: '1591753850917'
  alias: Notify when the weather station battery is low
  description: ''
  trigger:
  - entity_id: sensor.outdoor_battery_ok
    from: '1'
    platform: state
    to: '0'
  condition: []
  action:
  - data_template:
      message: Temperature sensor "{{ trigger.to_state.name }}" has a low battery
      title: Temp Sensor Battery Low
    service: notify.pushover
  mode: single
- id: '1596808784045'
  alias: Notify when master bedroom sensor battery is low
  description: ''
  trigger:
  - entity_id: sensor.master_bedroom_battery_ok
    from: '1'
    platform: state
    to: '0'
  - entity_id: sensor.east_bedroom_battery_ok
    from: '1'
    platform: state
    to: '0'
  - entity_id: sensor.west_bedroom_battery_ok
    from: '1'
    platform: state
    to: '0'
  - entity_id: sensor.north_bedroom_battery_ok
    from: '1'
    platform: state
    to: '0'
  condition: []
  action:
  - data:
      message: The master bedroom sensor battery is low.
      title: Temperature Sensor Battery
    service: notify.pushover
  mode: single
- id: '1599055993244'
  alias: Turn off chromecast when TV turns off
  description: ''
  trigger:
  - entity_id: media_player.home_theater_tv
    for: 00:00:05
    platform: state
    to: 'off'
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: media_player.chromecastultra9136
      state: 'off'
  action:
  - data: {}
    entity_id: media_player.chromecastultra9136
    service: media_player.turn_off
  mode: single
- id: '1602644611823'
  alias: High Sensitivity House
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.garage_door
    from: closed
  - platform: state
    entity_id: binary_sensor.motion_garage
    from: 'off'
  - platform: state
    entity_id: binary_sensor.motion_front_door
    from: 'off'
  condition: []
  action:
  - service: notify.pushover
    data:
      message: The {{ trigger.entity_id }} was triggered from {{ trigger.from_state
        }}
      title: Stuff is happening at home
  mode: single
- id: '1617384805887'
  alias: Work Desk
  description: ''
  trigger:
  - platform: time_pattern
    hours: '8'
    minutes: '0'
    seconds: '0'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: script.set_desk_light_to_at_work
  mode: single
- id: '1617385425384'
  alias: Weekday Fun Desk
  description: ''
  trigger:
  - platform: time_pattern
    hours: '17'
    minutes: '0'
    seconds: '0'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: script.set_desk_light_to_at_home
  mode: single
- id: '1617385468858'
  alias: Weekend Fun Desk
  description: ''
  trigger:
  - platform: time_pattern
    hours: '8'
    minutes: '0'
    seconds: '0'
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - service: script.set_desk_light_to_at_home
  mode: single
- id: '1618003272208'
  alias: Doorbell Rung
  description: Notify when doorbell is rung
  trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_doorbell
    to: 'on'
  condition: []
  action:
  - service: camera.snapshot
    target:
      entity_id: camera.doorbell_2
    data:
      filename: /tmp/doorbell
  - service: notify.pushover
    data:
      message: Someone is at the door
      title: Doorbell
      data:
        attachment: /tmp/doorbell
  mode: single
- id: '1620849253039'
  alias: Master Bedroom Fan On
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.master_bedroom_temperature
    above: '72'
  condition: []
  action:
  - service: fan.turn_on
    data:
      percentage: 33
    target:
      entity_id: fan.master_bedroom
  mode: single
- id: '1620968380218'
  alias: Master Bedroom Fan Off
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.master_bedroom_temperature
    below: '70'
  condition: []
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.master_bedroom
  mode: single
