- alias: "Outdoor Lights On When Dark"
  trigger: 
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: -4.0
  action:
    service: switch.turn_on
    entity_id: 
      - switch.front_door_south_switch
      - switch.garage_sconces_switch

- alias: "Outdoor Lights On When Dark and Cloudy"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: 0
  condition:
    - condition: numeric_state
      entity_id: 'sensor.dark_sky_cloud_cover'
      above: 80
  action:
    service: switch.turn_on
    entity_id: 
      - switch.front_door_south_switch
      - switch.garage_sconces_switch

- alias: "Porch Light Off At 11"
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: switch.turn_off
    entity_id:
      - switch.front_door_south_switch

- alias: "Outdoor Lights Off When Light and Cloudy"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    above: -4.0
  condition:
    - condition: numeric_state
      entity_id: 'sensor.dark_sky_cloud_cover'
      below: 80
  action:
    service: switch.turn_off
    entity_id: 
      - switch.front_door_south_switch
      - switch.garage_sconces_switch

- alias: "Outdoor Lights Off When Light"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    above: 0
  action:
    service: switch.turn_off
    entity_id: 
      - switch.front_door_south_switch
      - switch.garage_sconces_switch

- alias: "Dim theater lights for movies"
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('media_player.home_theater_tv', 'source', 'Plex') }}"
    - platform: template
      value_template: "{{ is_state_attr('media_player.home_theater_tv', 'source', 'Amazon Prime Video') }}"
    - platform: template
      value_template: "{{ is_state_attr('media_player.home_theater_tv', 'source', 'Netflix') }}"
    - platform: template
      value_template: "{{ is_state_attr('media_player.home_theater_tv', 'source', 'Google Play Movies & TV') }}"      
    - platform: template
      value_template: "{{ is_state_attr('media_player.home_theater_tv', 'source', 'Hulu') }}"      
    - platform: template
      value_template: "{{ is_state_attr('media_player.home_theater_tv', 'source', 'Watch a Movie') }}"      
  condition:
    condition: state
    entity_id: light.home_theater_west_dimmer
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.home_theater_west_dimmer
    data:
      brightness_pct: 10
      transition: 3

- alias: "Change light color for watching TV"
  trigger:
    platform: state
    entity_id: media_player.home_theater_tv
    from: 'off'
  condition:
    condition: state
    entity_id: light.basement_rgbw_controller_main
    state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.basement_rgbw_controller_red    
    - service: light.turn_off
      entity_id: light.basement_rgbw_controller_green
    - service: light.turn_off
      entity_id: light.basement_rgbw_controller_blue
    - service: light.turn_on
      entity_id: light.basement_rgbw_controller_white
      data:
        transition: 5
        brightness_pct: 30

- alias: "Brighten lights when done watching TV"
  trigger:
    platform: state
    entity_id: media_player.home_theater_tv
    to: 'off'
  condition:
    condition: state
    entity_id: light.home_theater_west_dimmer
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.home_theater_west_dimmer
    data:
      brightness_pct: 100
      transition: 3

- alias: "Change light color when done watching TV"
  trigger:
    platform: state
    entity_id: media_player.home_theater_tv
    to: 'off'
  condition:
    condition: state
    entity_id: light.basement_rgbw_controller_main
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.basement_rgbw_controller_main
    data:
      rgb_color: [255, 255, 255]
      transition: 5
      white_value: 255

- alias: "Turn off home theater lights if basement lights turn off"
  trigger:
    platform: state
    entity_id: light.basement_rgbw_controller_main
    to: 'off'
    for:
      seconds: 5
  condition:
    condition: state
    entity_id: light.home_theater_west_dimmer
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.home_theater_west_dimmer

- alias: "Notify when garage is open for too long"
  trigger:
    platform: state
    entity_id: sensor.garage_door
    to: 'Open'
    for:
      hours: 1
  action:
    service: notify.notify
    data_template: 
      message: "The garage door has been open longer than an hour"
    data:
      title: "Garage Door Open"
      data:
        sound: gamelan
      
- alias: "Notify when TV has been on for too long"
  trigger: 
    platform: state
    entity_id: media_player.home_theater_tv
    to: 'playing'
    for:
      hours: 3
  action:
    service: notify.notify
    data_template:
      message: "The TV has been on for longer than 3 hours"
    data:
      title: "TV is On"
      data:
        sound: tugboat
      
- alias: "Notify when printer is done printing"
  trigger: 
    platform: state
    entity_id: sensor.octoprint_current_state
    from: 'Printing'
  action:  
    - service: light.turn_on
      entity_id: light.f0fe6b5ac15e_192_168_1_50
      data:
        effect: colorloop
    - service: light.turn_on
      entity_id: light.f0fe6b5ac15e_192_168_1_50
      data:
        white_value: 0
    - service: notify.notify
      data_template:
        message: "The printer has finished printing"
      data:
        title: "3D Printer is Done"
        data:
          device: pixelxl

- alias: "Turn 3D printer light to white when printing"
  trigger:
      platform: state
      entity_id: sensor.octoprint_current_state
      to: 'Printing'
  action:
    - service: light.turn_on
      entity_id: light.f0fe6b5ac15e_192_168_1_50
      data:          
        white_value: 255
    - service: light.turn_on
      entity_id: light.f0fe6b5ac15e_192_168_1_50
      data:          
        rgb_color: [255,255,255]