- alias: "Porch Light On When Dark"
  trigger: 
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: -4.0
  action:
    service: switch.turn_on
    entity_id: switch.front_door_south_switch

- alias: "Porch Light Off When Light"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    above: -4.0
  action:
    service: switch.turn_off
    entity_id: switch.front_door_south_switch

- alias: "Turn Away Mode On When Away"
  trigger:
    platform: state
    entity_id: group.devices
    from: 'home'
    to: 'not_home'
    for:
      minutes: 45
  action:
    - service: media_player.turn_off
      data:
        entity_id: media_player.home_theater_tv
    - service: media_player.turn_off
      data:
        entity_id: media_player.living_room_audio

- alias: "Switch Kitchen Under Cabinet Lights On"
  trigger:
    platform: state
    entity_id: switch.kitchen_south_switch
    to: 'on'
  action:
    service: light.turn_on
    entity_id: 
      - light.kitchen_light_controller

- alias: "Switch Kitchen Under Cabinet Lights Off"
  trigger:
    platform: state
    entity_id: switch.kitchen_south_switch
    to: 'off'
  action:
    service: light.turn_off
    entity_id: 
      - light.kitchen_light_controller