- platform: mjpeg
  name: Ouranos
  still_image_url: !secret ouranos_still_url
  mjpeg_url: !secret ouranos_stream_url

- platform: mjpeg
  name: Gaia
  still_image_url: !secret gaia_still_url
  mjpeg_url: !secret gaia_stream_url

- platform: ffmpeg
  name: Nursery
  input: !secret nursery_camera_rtsp
  extra_arguments: "-use_wallclock_as_timestamps 1 -async 1 -vsync 1"