- platform: ffmpeg
  name: 3D Printer
  input: !secret 3d_printer_camera_rtsp

- platform: ffmpeg
  name: 3D Printer Filament
  input: !secret 3d_printer_filament_rtsp

- platform: ffmpeg
  name: Nursery
  input: !secret nursery_camera_rtsp