- platform: mjpeg
  mjpeg_url: http://technetium.local:8080/?action=stream
  still_image_url: http://technetium.local:8080/?action=snapshot
  name: 3dprinter

- platform: generic
  name: Garage
  still_image_url: !secret garage_camera_still
  stream_source: !secret garage_camera_rtsp

- platform: generic
  name: G3 Flex
  still_image_url: !secret g3_flex_camera_still
  stream_source: !secret g3_flex_camera_rtsp

- platform: generic
  name: Kids Room
  still_image_url: !secret kids_camera_still
  stream_source: !secret kids_camera_rtsp

  