- platform: generic
  still_image_url: !secret 3d_printer_camera_still
  stream_source: !secret 3d_printer_camera_rtsp
  name: 3D Printer

- platform: generic
  name: Garage
  still_image_url: !secret garage_camera_still
  stream_source: !secret garage_camera_rtsp

- platform: generic
  name: Front Door
  still_image_url: !secret front_door_camera_still
  stream_source: !secret front_door_camera_rtsp

- platform: generic
  name: Kids Room
  still_image_url: !secret kids_camera_still
  stream_source: !secret kids_camera_rtsp

- platform: generic
  name: Nursery
  still_image_url: !secret nursery_camera_still
  stream_source: !secret nursery_camera_rtsp