homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

frontend:

config:

http:
  api_password: !secret http_password
  server_port: 8123
  base_url: hassio.local
  trusted_networks:
    - 192.168.1.0/24

updater:
  include_used_components: true

discovery:

history:

logbook:

sun:

tts:
  - platform: google

mqtt:
  broker: core-mosquitto

wake_on_lan:

zwave:
  usb_path: /dev/ttyACM0

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

media_player:
  - platform: plex
  - platform: webostv
    host: !secret tv_ip_address 
    name: Home Theater TV
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret tv_mac_address

device_tracker:
  - platform: ping
    count: 5
    hosts:
      pixel_xl: !secret andrews_phone_ip_address
      moto_z_play: !secret marias_phone_ip_address
      cable_modem: !secret modem_ip_address
  - platform: nmap_tracker
    track_new_devices: false
    hosts: 
      - 192.168.1.1/24
    exclude:
      - !secret hassio_ip_address
      - !secret andrews_phone_ip_address
      - !secret marias_phone_ip_address

group: !include groups.yaml
automation: !include automations.yaml
script: !include_dir_merge_named script
sensor: !include sensors.yaml
