homeassistant:
  name: Home  
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
      - !secret local_network
      - !secret vpn_network
  auth_mfa_modules:
    - type: totp
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /tmp

default_config:
  
discovery:

frontend:
  themes: !include_dir_merge_named themes

http:
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies: 
    - 192.168.1.100
  ip_ban_enabled: true
  login_attempts_threshold: 5
  
light:
  - platform: flux_led
    devices:
      192.168.1.50:
        name: 3d_printer_lights
        mode: "rgbw"
        protocol: "ledenet"

octoprint:
  host: !secret gaia_ip_address
  api_key: !secret octoprint_api_key
  port: 80
  bed: true
  number_of_tools: 2

pi_hole:
  host: !secret heracles_ip_address
  api_key: !secret pihole_api_key

recorder:
  db_url: !secret mariadb_address
  purge_keep_days: 30
  purge_interval: 1

remote:
  - platform: harmony
    name: Harmony Hub
    host: !secret harmony_hub_ip_address

stream: 

tts:
  - platform: google_translate

unifiprotect:
  host: !secret unifi_protect_ip_address
  username: !secret unifi_protect_username
  password: !secret unifi_protect_password

wake_on_lan:

webostv:
  host: !secret tv_ip_address 
  name: Home Theater TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret tv_mac_address

zwave:
  usb_path: !secret zwave_stick_path
  device_config: !include zwave_device_config.yaml

camera: !include cameras.yaml
switch: !include switches.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
notify: !include notifications.yaml
script: !include scripts.yaml