homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

frontend:

config:

http:
  api_password: !secret http_password
  server_port: 8123
  base_url: hassio.local
  trusted_networks:
    - 192.168.1.0/24

updater:
  include_used_components: true

discovery:

history:

logbook:

sun:

sensor:
  - platform: darksky
    api_key: !secret dark_sky_key
    monitored_conditions:
      - summary
      - temperature
      - daily_summary
      - temperature_max
      - temperature_min

tts:
  - platform: google

mqtt:
  broker: core-mosquitto

wake_on_lan:

zwave:
  usb_path: /dev/ttyACM0

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

media_player:
  - platform: plex
  - platform: webostv
    host: !secret tv_ip_address 
    name: Home Theater TV
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret tv_mac_address

device_tracker:
  - platform: ping
    hosts:
      pixel_xl: 192.168.1.12
      moto_z_play: 192.168.1.14

group: !include groups.yaml
automation: !include automations.yaml
script: !include_dir_merge_named script
