homeassistant:
  name: Home  
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
      - !secret local_network
      - !secret vpn_network
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /tmp

frontend:
  themes: !include themes.yaml

system_health:

config:

cloud:

http:
  server_port: 8123
  base_url: hassio.local
      
updater:
  include_used_components: true

discovery:

history:

logbook:

recorder:
  db_url: !secret mariadb_address

sun:

tts:
  - platform: google_translate

mqtt:
  broker: core-mosquitto

wake_on_lan:

weather:
  - platform: darksky
    api_key: !secret dark_sky_key
    units: us

zwave:
  usb_path: /dev/ttyACM0

stream: 

light:
  - platform: flux_led
    devices:
      192.168.1.50:
        name: 3d_printer_lights
        mode: "rgbw"
        protocol: "ledenet"

unifi:
  controllers:
    - host: unifi
      site: Default

pi_hole:

octoprint:
  host: !secret gaia_ip_address
  api_key: !secret octoprint_api_key
  port: 80
  bed: true
  number_of_tools: 2

remote:
  - platform: harmony
    name: Harmony Hub
    host: !secret harmony_hub_ip_address

camera: !include cameras.yaml
switch: !include switches.yaml  
media_player: !include media_players.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include_dir_merge_named script
sensor: !include sensors.yaml
notify: !include notifications.yaml