Copy-Item -Path "\\homeassistant.local\config\configuration.yaml" -Force
Copy-Item -Path "\\homeassistant.local\config\automations.yaml" -Force
Copy-Item -Path "\\homeassistant.local\config\scripts.yaml" -Force
Copy-Item -Path "\\homeassistant.local\config\scenes.yaml" -Force
Copy-Item -Path "\\homeassistant.local\config\sensors.yaml" -Force
Copy-Item -Path "\\homeassistant.local\config\switches.yaml" -Force
Copy-Item -Path "\\homeassistant.local\config\notifications.yaml" -Force
Copy-Item -Path "\\homeassistant.local\config\customize.yaml" -Force
Copy-Item -Path "\\homeassistant.local\config\cameras.yaml" -Force
Copy-Item -Path "\\homeassistant.local\config\binary_sensors.yaml" -Force