- platform: darksky
  api_key: !secret dark_sky_key
  monitored_conditions:
    - apparent_temperature
    - apparent_temperature_min
    - apparent_temperature_max

- platform: pi_hole
  host: !secret pihole_ip_address
  monitored_conditions:
    - ads_percentage_today
    - dns_queries_today

- platform: speedtest
  server_id: 10143
  monitored_conditions:
    - ping
    - download
    - upload

- platform: template
  sensors:
    harmony_hub:
      value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
      friendly_name: 'Home Theater'      