- platform: template
  sensors:
    harmony_hub:
      value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
      friendly_name: 'Home Theater'      

- platform: template
  sensors:
    garage_door:
      value_template: "{% if states.binary_sensor.vision_zg8101_garage_door_detector_sensor.state == 'on' %}Open{% elif states.sensor.vision_zg8101_garage_door_detector_alarm_level.state == '255' %}Open{% else %}Closed{% endif %}"
      friendly_name: 'Garage Door Sensor'

- platform: template
  sensors:
    garage_door_sensor_battery_level:
      value_template: '{{ states.zwave.vision_zg8101_garage_door_detector.attributes.battery_level }}'
      friendly_name: 'Garage Door Sensor Battery Level'

- platform: my_unifi
  username: !secret unifi_username
  password: !secret unifi_password
  url: !secret unifi_url