- platform: template
  sensors:
    harmony_hub:
      value_template: '{{ states.remote.home_theater.attributes.current_activity }}'
      friendly_name: 'Home Theater'

###### Master Bedroom Temp/Humid #####
- platform: mqtt
  name: "Master Bedroom Temperature"
  state_topic: "rtl_433/15454/state"
  device_class: temperature
  value_template: "{{ value_json.temperature_F }}"
  unit_of_measurement: '°F'
- platform: mqtt
  name: "Master Bedroom Humidity"
  state_topic: "rtl_433/15454/state"
  device_class: humidity
  unit_of_measurement: '%'
  value_template: "{{ value_json.humidity }}"
- platform: mqtt
  name: "Master Bedroom Battery OK"
  state_topic: "rtl_433/15454/battery_ok"
  value_template: "{{ value_json.battery_ok }}"

###### Outdoor 5-in-1 Sensor #####
- platform: mqtt
  name: "Outside Temperature"
  state_topic: "rtl_433/1309/state"
  device_class: temperature
  unit_of_measurement: '°F'
  value_template: "{{ value_json.temperature_F }}"
- platform: mqtt
  name: "Outside Humidity"
  state_topic: "rtl_433/1309/state"
  device_class: humidity
  unit_of_measurement: '%'
  value_template: "{{ value_json.humidity }}"
- platform: mqtt
  name: "Total Rainfall"
  state_topic: "rtl_433/1309/state"
  unit_of_measurement: 'in'
  value_template: "{{ value_json.rain_in }}"
- platform: mqtt
  name: "Outside Wind Speed"
  state_topic: "rtl_433/1309/state"
  unit_of_measurement: 'mph'  
  value_template: "{{ value_json.wind_avg_mi_h }}"
- platform: mqtt
  name: "Outside Wind Direction"
  state_topic: "rtl_433/1309/state"
  unit_of_measurement: '°'
  value_template: "{{ value_json.wind_dir_deg }}"
- platform: mqtt
  name: "Outdoor Battery OK"
  state_topic: "rtl_433/1309/state"
  value_template: "{{ value_json.battery_ok }}"

###### North Bedroom Temp/Humid #####
- platform: mqtt
  name: "North Bedroom Temperature"
  state_topic: "rtl_433/6781/state"
  device_class: temperature
  unit_of_measurement: '°F'
  value_template: "{{ value_json.temperature_F }}"
- platform: mqtt
  name: "North Bedroom Humidity"
  state_topic: "rtl_433/6781/state"
  device_class: humidity
  unit_of_measurement: '%'
  value_template: "{{ value_json.humidity }}"
- platform: mqtt
  name: "North Bedroom Battery OK"
  state_topic: "rtl_433/6781/state"
  value_template: "{{ value_json.battery_ok }}"

###### West Bedroom Temp/Humid #####
- platform: mqtt
  name: "West Bedroom Temperature"
  state_topic: "rtl_433/6734/state"
  device_class: temperature
  unit_of_measurement: '°F'
  value_template: "{{ value_json.temperature_F }}"
- platform: mqtt
  name: "West Bedroom Humidity"
  state_topic: "rtl_433/6734/state"
  device_class: humidity
  unit_of_measurement: '%'
  value_template: "{{ value_json.humidity }}"
- platform: mqtt
  name: "West Bedroom Battery OK"
  state_topic: "rtl_433/6734/state"
  value_template: "{{ value_json.battery_ok }}"

###### East Bedroom Temp/Humid #####
- platform: mqtt
  name: "East Bedroom Temperature"
  state_topic: "rtl_433/890/state"
  device_class: temperature
  unit_of_measurement: '°F'
  value_template: "{{ value_json.temperature_F }}"
- platform: mqtt
  name: "East Bedroom Humidity"
  state_topic: "rtl_433/890/state"
  device_class: humidity
  unit_of_measurement: '%'
  value_template: "{{ value_json.humidity }}"
- platform: mqtt
  name: "East Bedroom Battery OK"
  state_topic: "rtl_433/890/state"
  value_template: "{{ value_json.battery_ok }}"