- platform: template
  sensors:
    harmony_hub:
      value_template: '{{ states.remote.home_theater.attributes.current_activity }}'
      friendly_name: 'Home Theater'

###### Master Bedroom Temp/Humid #####
- platform: mqtt
  name: "Master Bedroom Temperature"
  state_topic: "rtl_433/15454/temperature_F"
  device_class: temperature
  unit_of_measurement: '°F'
- platform: mqtt
  name: "Master Bedroom Humidity"
  state_topic: "rtl_433/15454/humidity"
  device_class: humidity
  unit_of_measurement: '%'
- platform: mqtt
  name: "Master Bedroom Battery OK"
  state_topic: "rtl_433/15454/battery_ok"

###### Outdoor 5-in-1 Sensor #####
- platform: mqtt
  name: "Outside Temperature"
  state_topic: "rtl_433/1309/temperature_F"
  device_class: temperature
  unit_of_measurement: '°F'
- platform: mqtt
  name: "Outside Humidity"
  state_topic: "rtl_433/1309/humidity"
  device_class: humidity
  unit_of_measurement: '%'
- platform: mqtt
  name: "Total Rainfall"
  state_topic: "rtl_433/1309/rain_in"
  unit_of_measurement: 'in'
- platform: mqtt
  name: "Outside Wind Speed"
  state_topic: "rtl_433/1309/wind_avg_mi_h"
  unit_of_measurement: 'mph'  
- platform: mqtt
  name: "Outside Wind Direction"
  state_topic: "rtl_433/1309/wind_dir_deg"
  unit_of_measurement: '°'
- platform: mqtt
  name: "Outdoor Battery OK"
  state_topic: "rtl_433/1309/battery_ok"

###### North Bedroom Temp/Humid #####
- platform: mqtt
  name: "North Bedroom Temperature"
  state_topic: "rtl_433/6781/temperature_F"
  device_class: temperature
  unit_of_measurement: '°F'
- platform: mqtt
  name: "North Bedroom Humidity"
  state_topic: "rtl_433/6781/humidity"
  device_class: humidity
  unit_of_measurement: '%'
- platform: mqtt
  name: "North Bedroom Battery OK"
  state_topic: "rtl_433/6781/battery_ok"

###### West Bedroom Temp/Humid #####
- platform: mqtt
  name: "West Bedroom Temperature"
  state_topic: "rtl_433/6734/temperature_F"
  device_class: temperature
  unit_of_measurement: '°F'
- platform: mqtt
  name: "West Bedroom Humidity"
  state_topic: "rtl_433/6734/humidity"
  device_class: humidity
  unit_of_measurement: '%'
- platform: mqtt
  name: "West Bedroom Battery OK"
  state_topic: "rtl_433/6734/battery_ok"

###### East Bedroom Temp/Humid #####
- platform: mqtt
  name: "East Bedroom Temperature"
  state_topic: "rtl_433/890/temperature_F"
  device_class: temperature
  unit_of_measurement: '°F'
- platform: mqtt
  name: "East Bedroom Humidity"
  state_topic: "rtl_433/890/humidity"
  device_class: humidity
  unit_of_measurement: '%'
- platform: mqtt
  name: "East Bedroom Battery OK"
  state_topic: "rtl_433/890/battery_ok"

###### Living Room Temp/Humid #####
- platform: mqtt
  name: "Living Room Temperature"
  state_topic: "rtl_433/54/temperature_F"
  device_class: temperature
  unit_of_measurement: '°F'
- platform: mqtt
  name: "Living Room Humidity"
  state_topic: "rtl_433/54/humidity"
  device_class: humidity
  unit_of_measurement: '%'
- platform: mqtt
  name: "Living Room Battery OK"
  state_topic: "rtl_433/54/battery_ok"

###### Electricity Meter #####
- platform: mqtt
  name: "Electricity Consumption"
  state_topic: "rtl_433/64633980/consumption_data"
  device_class: energy
  unit_of_measurement: 'kWh'