- platform: flux
  lights:
    - light.kitchen_light_controller
  mode: rgb
  start_colortemp: 15000
  disable_brightness_adjust: true
- platform: template
  switches:
    watch_netflix_amazon:
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch Netflix/Hulu/Plex/Amazon') }}"
      turn_on:
        service: remote.turn_on
        entity_id: remote.harmony_hub 
        data:
          activity: "31723829"
      turn_off:
        service: remote.turn_off
        entity_id: remote.harmony_hub
        data:
          activity: "-1"
    watch_a_movie:
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch a Movie') }}"
      turn_on:
        service: remote.turn_on
        entity_id: remote.harmony_hub 
        data:
          activity: "31991234"
      turn_off:
        service: remote.turn_off
        entity_id: remote.harmony_hub
        data:
          activity: "-1"
    watch_tv:
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch TV') }}"
      turn_on:
        service: remote.turn_on
        entity_id: remote.harmony_hub 
        data:
          activity: "31723708"
      turn_off:
        service: remote.turn_off
        entity_id: remote.harmony_hub
        data:
          activity: "-1"
    play_switch:
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Play Switch') }}"
      turn_on:
        service: remote.turn_on
        entity_id: remote.harmony_hub 
        data:
          activity: "31724466"
      turn_off:
        service: remote.turn_off
        entity_id: remote.harmony_hub
        data:
          activity: "-1"
    play_steam_link:
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Play Steam Link') }}"
      turn_on:
        service: remote.turn_on
        entity_id: remote.harmony_hub 
        data:
          activity: "31724685"
      turn_off:
        service: remote.turn_off
        entity_id: remote.harmony_hub
        data:
          activity: "-1"
    listen_to_bluetooth:
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Listen to Bluetooth') }}"
      turn_on:
        service: remote.turn_on
        entity_id: remote.harmony_hub 
        data:
          activity: "Listen to Bluetooth"
      turn_off:
        service: remote.turn_off
        entity_id: remote.harmony_hub
        data:
          activity: "-1"